id: P000136
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། འཇམ་མགོན་བླ་མ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོའི་རྣམ་ཐར་གསོལ་འདེབས་ཀྱི་འགྲེལ་བ་མཚོ་བྱུང་དཔལ་མོ་དགྱེས་པའི་རྒྱུད་མང་ཞེས་བྱ་བ་བཞུགས།
    །
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - quotation
  - sabche
  - yigchung
  id: SHE-DKR-13
web_metadata:
  title:
    en: A Lute Bringing Joy to Sarasvati:A Commentary on the Verse Biography of Mipham
    bo: འཇམ་མགོན་བླ་མ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོའི་རྣམ་ཐར་གསོལ་འདེབས་ཀྱི་འགྲེལ་བ་མཚོ་བྱུང་དཔལ་མོ་དགྱེས་པའི་རྒྱུད་མང་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Dilgo Khyentse Series–  Book 13
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༡༣
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-13
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-13.epub
  description:
    en: ''
    bo: ''
